bundle:
  groupId: "io.jenkins.tools.custom-war-packager.demo"
  artifactId: "jenkinsfile-runner"
  vendor: "Jenkins project"
  title: "Jenkinsfile Runner demo"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"
buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        noCache: true
      source:
        dir: ./source
    docker:
      base: "openjdk:8-jdk"
      tag: "jenkins-experimental/jenkinsfile-runner-demo"
      build: false
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.277.2"
plugins:
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1.73"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "2.39"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "2.81"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "2.40"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "2.22"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "2.11"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "3.5"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.6.1"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.14"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "2.3.12"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "1.20"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "2.6.3"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "1.18.1"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "1.32"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "1.23"
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.41"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "1.34"
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-as-yaml"
    source:
      version: "0.12-rc"
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.26.4"
systemProperties: {
    jenkins.model.Jenkins.slaveAgentPort: "50000",
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"}
